#! /bin/sh

# Tool to install/remove commands to a-Shell
#
# options:
# install packageName: pull server/packageName.pkg, execute script packageName.pkg, create .pkg/packageName
# remove packageName: execute .pkg/packageName
# list: show all installed packages
# search + regexp: pull list from server, grep with regexp
# server: change address of package server

# main url. Can be overidden by environment variable
if [ -z "$SERVER" ]
then
	server=https://raw.githubusercontent.com/holzschu/a-Shell-commands/master/
else
	server=$SERVER
fi

usage() {
cat << 'EOF'
Usage: pkg [install name] [remove name] [list] [search expression] [server]
  install: installs package "name"
  remove: removes package "name"
  list: list all installed packages
  search: lists packages matching expression
  server: changes package server
EOF
}

list() {
	ls -1 ~/Documents/.pkg/
}

search() {
	echo Packages available:
	if [ -z $1 ]
	then
		curl -L $server/list --silent
	else
		expression=$1
		curl -L $server/list --silent | grep $expression
	fi
}

install() {
	name=$1
	curl -L $server/list --silent | grep $name > ~/tmp/packageList
	length=`wc -l < ~/tmp/packageList`
	if [ $length -eq 0 ]
	then
		echo Package $name not found
	elif [ $length -eq 1 ]
	then
		packageName=`cat ~/tmp/packageList`
		echo Downloading $packageName
		curl -L $server/packages/$packageName -o ~/tmp/$packageName --silent
		chmod +x ~/tmp/$packageName
		sh ~/tmp/$packageName
		rm ~/tmp/$packageName
		echo Done
	else
		echo Package $name unclear. Did you mean:
		cat ~/tmp/packageList
	fi
	rm ~/tmp/packageList
}

remove() {
	name=$1
	if [ -f ~/Documents/.pkg/$name ]
	then
		echo Removing $name
		sh ~/Documents/.pkg/$name
		rm ~/Documents/.pkg/$name
		mandocdb ~/Library/man
		echo Done
	else
		echo Package $name was not installed by pkg. Cannot remove it.
	fi
}

server() {
	# TODO: check that the change is permanent (and for how long)
	server=$1
	export SERVER=$server
}

case $1 in
	# TODO: allow for multiple install (for loop on all arguments except first one)
	install) install $2;;
	update) install $2;;
	upgrade) install $2;;
	list) list;;
	remove) remove $2;;
	server) server $2;;
	search) search $2;;
	*) usage
esac
