.TH GLOW 1 "2026-08-11" "glow" "Render markdown on the CLI, with pizzazz!"
.SH NAME
glow - Render markdown on the CLI, with pizzazz!
.SH SYNOPSIS
\fBglow\fP [\fIoptions\&.\&.\&.\fP] [\fIargument\&.\&.\&.\fP]
.SH DESCRIPTION
                                                                              
.PP
  Render markdown on the CLI, [38;2;4;181;117mwith pizzazz[m!                                   
.SH OPTIONS
.TP
\fB-a, --all\fP
show system files and directories (TUI-mode only)
.TP
\fB--config\fP
config file (default /home/runner/\&.config/glow/glow\&.yml)
.TP
\fB-l, --line-numbers\fP
show line numbers (TUI-mode only)
.TP
\fB-m, --mouse\fP
enable mouse wheel (TUI-mode only)
.TP
\fB-p, --pager\fP
display with pager
.TP
\fB-n, --preserve-new-lines\fP
preserve newlines in the output
.TP
\fB-s, --style\fP
style name or JSON path
.TP
\fB-t, --tui\fP
display with tui
.TP
\fB-w, --width\fP
word-wrap at width (set to 0 to disable)
.SH COMMANDS
.TP
\fBcompletion\fP
.RS 4
Generate the autocompletion script for the specified shell
.RE
.TP
\fBCOMMANDS\fP
.RS 4
\fBbash\fP
.RS 4
Generate the autocompletion script for bash
.RE
.TP
\fBOPTIONS\fP
.RS 4
\fB--no-descriptions\fP
disable completion descriptions
.RE
.TP
\fBfish\fP
.RS 4
Generate the autocompletion script for fish
.RE
.TP
\fBOPTIONS\fP
.RS 4
\fB--no-descriptions\fP
disable completion descriptions
.RE
.TP
\fBpowershell\fP
.RS 4
Generate the autocompletion script for powershell
.RE
.TP
\fBOPTIONS\fP
.RS 4
\fB--no-descriptions\fP
disable completion descriptions
.RE
.TP
\fBzsh\fP
.RS 4
Generate the autocompletion script for zsh
.RE
.TP
\fBOPTIONS\fP
.RS 4
\fB--no-descriptions\fP
disable completion descriptions
.RE
.RE
.TP
\fBconfig\fP
.RS 4
Edit the glow config file
.RE
.TP
\fBEXAMPLES\fP
.RS 4
  glow config                                                                 
.PP
  glow config --config path/to/config\&.yml                                     
.RE
.TP
\fBhelp\fP [command]
.RS 4
Help about any command
.RE
