#! /bin/sh
# remove command
rm -f ~/Documents/bin/f2c
# libf2c.a was installed in two places; delete both:
rm -f ~/Library/lib/wasm32-wasi/libf2c.a
rm -f ~/Library/usr/lib/wasm32-wasi/libf2c.a
rm -f ~/Library/usr/include/wasm32-wasi/f2c.h
# remove man page
rm -f ~/Library/man/man1/f2c.1
# refresh man database
mandocdb ~/Library/man
#

