#! /bin/sh

# Default uninstall file for packages:
packagename=${0##*/}

# remove command
rm ~/Documents/bin/figlet.wasm3 
rm ~/Documents/bin/chkfont.wasm3 
rm ~/Documents/bin/figlist 
rm ~/Documents/bin/showfigfonts
rm -rf ~/Documents/.figlet_fonts
rm ~/Library/man/man6/figlet.6 
rm ~/Library/man/man6/chkfont.6 
rm ~/Library/man/man6/figlist.6 
rm ~/Library/man/man6/showfigfonts.6
# refresh man database
mandocdb ~/Library/man
