#! /bin/sh

# Default uninstall file for packages:
packagename=${0##*/}

# remove commands
rm ~/Documents/bin/acyclic
rm ~/Documents/bin/bcomps
rm ~/Documents/bin/ccomps
rm ~/Documents/bin/cluster
rm ~/Documents/bin/diffimg
rm ~/Documents/bin/dijkstra
rm ~/Documents/bin/dot
rm ~/Documents/bin/dot2gxl
rm ~/Documents/bin/edgepaint
rm ~/Documents/bin/gc
rm ~/Documents/bin/gml2gv
rm ~/Documents/bin/graphml2gv
rm ~/Documents/bin/gv2gml
rm ~/Documents/bin/gv2gxl
rm ~/Documents/bin/gvcolor
rm ~/Documents/bin/gvgen
rm ~/Documents/bin/gvmap
rm ~/Documents/bin/gvmap.sh
rm ~/Documents/bin/gvpack
rm ~/Documents/bin/gvpr
rm ~/Documents/bin/gxl2dot
rm ~/Documents/bin/gxl2gv
rm ~/Documents/bin/mm2gv
rm ~/Documents/bin/nop
rm ~/Documents/bin/prune
rm ~/Documents/bin/sccmap
rm ~/Documents/bin/tred
rm ~/Documents/bin/unflatten
# remove man pages
rm ~/Library/man/man1/acyclic.1
rm ~/Library/man/man1/bcomps.1
rm ~/Library/man/man1/ccomps.1
rm ~/Library/man/man1/circo.1
rm ~/Library/man/man1/cluster.1
rm ~/Library/man/man1/diffimg.1
rm ~/Library/man/man1/dijkstra.1
rm ~/Library/man/man1/dot.1
rm ~/Library/man/man1/dot2gxl.1
rm ~/Library/man/man1/edgepaint.1
rm ~/Library/man/man1/fdp.1
rm ~/Library/man/man1/gc.1
rm ~/Library/man/man1/gml2gv.1
rm ~/Library/man/man1/graphml2gv.1
rm ~/Library/man/man1/gv2gml.1
rm ~/Library/man/man1/gv2gxl.1
rm ~/Library/man/man1/gvcolor.1
rm ~/Library/man/man1/gvgen.1
rm ~/Library/man/man1/gvmap.1
rm ~/Library/man/man1/gvmap.sh.1
rm ~/Library/man/man1/gvpack.1
rm ~/Library/man/man1/gvpr.1
rm ~/Library/man/man1/gxl2dot.1
rm ~/Library/man/man1/gxl2gv.1
rm ~/Library/man/man1/mm2gv.1
rm ~/Library/man/man1/neato.1
rm ~/Library/man/man1/nop.1
rm ~/Library/man/man1/osage.1
rm ~/Library/man/man1/patchwork.1
rm ~/Library/man/man1/prune.1
rm ~/Library/man/man1/sccmap.1
rm ~/Library/man/man1/sfdp.1
rm ~/Library/man/man1/tred.1
rm ~/Library/man/man1/twopi.1
rm ~/Library/man/man1/unflatten.1
rm ~/Library/man/man7/graphviz.7
# refresh man database
mandocdb ~/Library/man
