#! /bin/sh

# Default uninstall file for packages:
packagename=`basename $0`

# remove command
rm ~/Documents/bin/$packagename
# remove dictionary 
rm ~/Library/usr/share/dict/words

# remove man page
rm ~/Library/man/man1/$packagename.1
# refresh man database
mandocdb ~/Library/man
