#! /bin/sh
# remove command
rm -f ~/Documents/bin/lzmadec.wasm
rm -f ~/Documents/bin/lzmainfo.wasm
rm -f ~/Documents/bin/lzmadec.wasm3
rm -f ~/Documents/bin/lzmainfo.wasm3
# remove man page
rm ~/Library/man/man1/lzmadec.1
rm ~/Library/man/man1/lzmainfo.1
# refresh man database
mandocdb ~/Library/man
#

