#! /bin/sh

# Default uninstall file for packages:
packagename=${0##*/}

# remove command
rm ~/Documents/bin/$packagename
# remove man page
rm ~/Library/man/man1/$packagename.1

# uninstall dirname and expr, but only if they weren't installed separately:

if [ -f ~/Documents/.pkg/mktemp ]
then
    echo "Not removing mktemp (installed separately)"
else
	echo "Removing mktemp"
	rm ~/Documents/bin/mktemp
	rm ~/Library/man/man1/mktemp.1
fi

# refresh man database
mandocdb ~/Library/man
