#! /bin/sh

# Default uninstall file for packages:
packagename=${0##*/}

rm -rf ~/Library/texlive/2024/texmf-dist/fonts/opentype
rm -rf ~/Library/texlive/2024/texmf-dist/fonts/truetype
# update commands list:
updateCommands
