#! /bin/sh
# remove command
rm -f ~/Documents/bin/xz
rm -f ~/Documents/bin/xzdec
rm -f ~/Documents/bin/xz.wasm3
rm -f ~/Documents/bin/xzdec.wasm3
# remove man page
rm ~/Library/man/man1/xz.1
rm ~/Library/man/man1/xzdec.1
# refresh man database
mandocdb ~/Library/man
#

