#! /bin/sh
for command in funzip unzip unzipsfx zip zipcloak zipnote zipsplit
do
    # remove command
    rm -f ~/Documents/bin/$command.wasm
    rm -f ~/Documents/bin/$command.wasm3
    # remove man page
    rm ~/Library/man/man1/$command.1
done
# refresh man database
mandocdb ~/Library/man
